const hotDealsSample = [
  {
    rating: 4.5,
    discount: 20,
    image: "./assets/golfimages/andrew-rice-waE_CT2q8Os-unsplash.jpg",
    time: "8:00 AM",
    clubName: "Club 1",
    price: 100,
    discountedPrice: 80,
    location: "Location 1",
    length: 7000,
    holes: 18,
    cart: true,
    player: 1,
  },
  {
    rating: 4.2,
    discount: 15,
    image: "./assets/golfimages/brenda-lai-7YnghE7AD7o-unsplash.jpg",
    time: "9:00 AM",
    clubName: "Club 2",
    price: 120,
    discountedPrice: 102,
    location: "Location 2",
    length: 6500,
    holes: 18,
    cart: true,
    player: 1,
  },
  {
    rating: 4.2,
    discount: 15,
    image: "./assets/golfimages/jorge-zapata-OTJ-xsNTk7Y-unsplash.jpg",
    time: "9:00 AM",
    clubName: "Club 2",
    price: 120,
    discountedPrice: 102,
    location: "Location 2",
    length: 6500,
    holes: 18,
    cart: true,
    player: 1,
  },
  {
    rating: 4.2,
    discount: 15,
    image: "./assets/golfimages/luis-feliciano-LQU_PI_hn2c-unsplash.jpg",
    time: "9:00 AM",
    clubName: "Club 2",
    price: 120,
    discountedPrice: 102,
    location: "Location 2",
    length: 6500,
    holes: 18,
    cart: true,
    player: 1,
  },
  {
    rating: 4.2,
    discount: 15,
    image: "./assets/golfimages/andrew-rice-waE_CT2q8Os-unsplash.jpg",
    time: "9:00 AM",
    clubName: "Club 2",
    price: 120,
    discountedPrice: 102,
    location: "Location 2",
    length: 6500,
    holes: 18,
    cart: true,
    player: 1,
  },
  {
    rating: 4.5,
    discount: 20,
    image: "./assets/golfimages/andrew-rice-waE_CT2q8Os-unsplash.jpg",
    time: "8:00 AM",
    clubName: "Club 1",
    price: 100,
    discountedPrice: 80,
    location: "Location 1",
    length: 7000,
    holes: 18,
    cart: true,
    player: 1,
  },
  {
    rating: 4.2,
    discount: 15,
    image: "./assets/golfimages/brenda-lai-7YnghE7AD7o-unsplash.jpg",
    time: "9:00 AM",
    clubName: "Club 2",
    price: 120,
    discountedPrice: 102,
    location: "Location 2",
    length: 6500,
    holes: 18,
    cart: true,
    player: 1,
  },
  {
    rating: 4.2,
    discount: 15,
    image: "./assets/golfimages/jorge-zapata-OTJ-xsNTk7Y-unsplash.jpg",
    time: "9:00 AM",
    clubName: "Club 2",
    price: 120,
    discountedPrice: 102,
    location: "Location 2",
    length: 6500,
    holes: 18,
    cart: true,
    player: 1,
  },
  {
    rating: 4.2,
    discount: 15,
    image: "./assets/golfimages/luis-feliciano-LQU_PI_hn2c-unsplash.jpg",
    time: "9:00 AM",
    clubName: "Club 2",
    price: 120,
    discountedPrice: 102,
    location: "Location 2",
    length: 6500,
    holes: 18,
    cart: true,
    player: 1,
  },
];

const GolfCitySample = [
  {
    city: "City1",
    location: "Location 1",
    imageUrl: "./assets/cityimages/arkadiusz-radek-VqOWqZoFazE-unsplash.jpg",
  },
  {
    city: "City1",
    location: "Location 1",
    imageUrl: "./assets/cityimages/arkadiusz-radek-VqOWqZoFazE-unsplash.jpg",
  },
  {
    city: "City1",
    location: "Location 1",
    imageUrl: "./assets/cityimages/fineas-anton-VV_AtjLknlA-unsplash.jpg",
  },
  {
    city: "City1",
    location: "Location 1",
    imageUrl: "./assets/cityimages/fons-heijnsbroek-_ayoDSVCSLQ-unsplash.jpg",
  },
  {
    city: "City1",
    location: "Location 1",
    imageUrl: "./assets/cityimages/freddie-marriage-IB9AOO-36yI-unsplash.jpg",
  },
  {
    city: "City1",
    location: "Location 1",
    imageUrl: "./assets/cityimages/arkadiusz-radek-VqOWqZoFazE-unsplash.jpg",
  },
  {
    city: "City1",
    location: "Location 1",
    imageUrl: "./assets/cityimages/arkadiusz-radek-VqOWqZoFazE-unsplash.jpg",
  },
  {
    city: "City1",
    location: "Location 1",
    imageUrl: "./assets/cityimages/fineas-anton-VV_AtjLknlA-unsplash.jpg",
  },
  {
    city: "City1",
    location: "Location 1",
    imageUrl: "./assets/cityimages/fons-heijnsbroek-_ayoDSVCSLQ-unsplash.jpg",
  },
  {
    city: "City1",
    location: "Location 1",
    imageUrl: "./assets/cityimages/freddie-marriage-IB9AOO-36yI-unsplash.jpg",
  },
];

const StayAndPlaysample = [
  {
    event: "event 1",
    people: 2,
    cost: 100,
    days: 2,
    imageUrl: "./assets/cityimages/arkadiusz-radek-VqOWqZoFazE-unsplash.jpg",
  },
  {
    event: "event 1",
    people: 2,
    cost: 100,
    days: 2,
    imageUrl: "./assets/cityimages/arkadiusz-radek-VqOWqZoFazE-unsplash.jpg",
  },
  {
    event: "event 1",
    people: 2,
    cost: 100,
    days: 2,
    imageUrl: "./assets/cityimages/fineas-anton-VV_AtjLknlA-unsplash.jpg",
  },
  {
    event: "event 1",
    people: 2,
    cost: 100,
    days: 2,
    imageUrl: "./assets/cityimages/fons-heijnsbroek-_ayoDSVCSLQ-unsplash.jpg",
  },
  {
    event: "event 1",
    people: 2,
    cost: 100,
    days: 2,
    imageUrl: "./assets/cityimages/freddie-marriage-IB9AOO-36yI-unsplash.jpg",
  },
];
export { hotDealsSample, GolfCitySample, StayAndPlaysample };
